config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :cases, :incidents

  root to: 'cases#index'

end

app/models/case.rb
class Case < ActiveRecord::Base
  has_one :incident
  belongs_to :user

  validates :name, presence: true
  validates :main_type, presence: true
  validates :sub_type, presence: true
end

app/models/incident.rb
class Incident < ActiveRecord::Base
  belongs_to :case

  has_attached_file :police_report
  validates_attachment_size :police_report, :less_than => 10.megabytes
  validates_attachment_content_type :police_report, :content_type =>
      %w('application/pdf","application/vnd.ms-excel',
       'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
       'application/msword',
       'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
       'text/plain')
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_one :case

  validates :login, presence: true, length: { minimum: 2, maximum: 20 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :login
  end
end

app/controllers/cases_controller.rb
class CasesController < ApplicationController
  before_filter :authenticate_user!

  def index
    @cases = Case.all
  end

  def show
    @case = Case.find params[:id]
    @incident = @case.incident unless @case.nil?
  end

  def edit
    @case = Case.find params[:id]
    @incident = @case.incident unless @case.nil?
  end

  def new
    @case = Case.new
  end

  def update
    @case = Case.find(params[:id])

    if @case.update(case_params)
      redirect_to @case
    else
      redirect_to edit_case_path(@case)
    end
  end

  def create
    @case = Case.new(case_params)
    if @case.save
      redirect_to @case
    else
      redirect_to new_case_path
    end
  end

  private
  def case_params
    params.require(:case).permit(:name, :number, :doc_number, :judge, :court, :plaintiff, :defendant,
                                 :corporation, :status, :creation_date, :date_closed, :date_closed,
                                 :main_type, :sub_type, :description)
  end
end

app/controllers/incidents_controller.rb
class IncidentsController < ApplicationController
  before_filter :authenticate_user!

  def show
    if Incident.where(id: params[:id]).empty?
      redirect_to new_incident_path
    else
      @incident = Incident.find params[:id]
    end
  end

  def edit
    @incident = Incident.find params[:id]
  end

  def new
    @incident = Incident.new
  end

  def update
    @incident = Incident.find params[:id]

    if @incident.update(incident_params)
      redirect_to @incident
    else
      redirect_to edit_incident_path_path(@incident)
    end
  end

  def create
    @incident = Incident.new(incident_params)
    if @incident.save
      redirect_to @incident
    else
      redirect_to new_incident_path
    end
  end

  private
  def incident_params
    params.require(:case).permit(:date_of_incident, :statute_of_limitations, :liability, :alcohol,
                                 :weather_factor, :damage, :airbag, :speed)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cases_helper.rb
module CasesHelper
end

app/helpers/incidents_helper.rb
module IncidentsHelper
end

app/views/cases/_form.html.haml
-if @case.errors.any?
  -@case.errors.full_messages.each do |error|
    \- #{ error.to_s}
    %br
=simple_form_for @case, html: { class: 'form-horizontal', multipart: true } do |f|
  %fieldset
    %legend
      =controller.action_name.capitalize
      case:
    .control-group
      =f.input :name, label: 'Case name'
      =f.input :number
      =f.input :doc_number, label: 'Docket no.'
      =f.input :judge
      =f.input :court
      =f.input :plaintiff
      =f.input :defendant
      =f.input :corporation
      =f.input :status
      =f.input :creation_date
      =f.input :date_closed
      =f.input :main_type, label: 'Type'
      =f.input :sub_type, label: 'Sub-type'
      =f.input :description
      %br
      =f.button :submit, class: 'btn btn-primary'

app/views/cases/edit.html.haml
= render partial: 'form'

app/views/cases/index.html.haml
%p
=link_to (button_tag 'NEW CASE', id: 'new_case_btn'), new_case_path
%h3 Cases
%table{id: 'index_case_table'}
  %thead
    %tr
      %td
        %strong Name
      %td
        %strong Number
      %td
        %strong Case Type
      %td
        %strong Sub-type
      %td
        %strong Description
      %td
        %strong Medical Bills
      %td
        
  %tbody
    -@cases.each do |case_var|
      %tr
        %td
          =case_var.name
        %td
          =case_var.number
        %td
          =case_var.main_type
        %td
          =case_var.sub_type
        %td
          =case_var.description
        %td
          -if case_var.incident.nil?
            0.0$
          -else
            =case_var.incident.damage.concat('$')
        %td
          =link_to 'Show', case_path(case_var)

app/views/cases/new.html.haml
= render partial: 'form'

app/views/cases/show.html.haml
%h3 Case Details
%br
%table{id: 'show_case_table'}
  %tr
    %td
      %strong Case name*:
    %td
      =@case.name
  %tr
    %td
      %strong Docket no.:
    %td
      =@case.doc_number
  %tr
    %td
      %strong Judge:
    %td
      =@case.judge
  %tr
    %td
      %strong court:
    %td
      =@case.court
  %tr
    %td
      %strong plaintiff:
    %td
      =@case.plaintiff
  %tr
    %td
      %strong Defendant:
    %td
      =@case.defendant
  %tr
    %td
      %strong corporation:
    %td
      -if @case.corporation
        Yes
      -else
        No
  %tr
    %td
      %strong Status:
    %td
      =@case.status
  %tr
    %td
      %strong Creation Date:
    %td
      =@case.creation_date
  %tr
    %td
      %strong Date Closed:
    %td
      =@case.date_closed
  %tr
    %td
      %strong Type*:
    %td
      =@case.main_type
  %tr
    %td
      %strong Sub-type:
    %td
      =@case.sub_type
  %tr
    %td
      %strong Description:
    %td
      =@case.description
%br
#links
  =link_to 'Edit', edit_case_path(@case)
  |
  =link_to 'Back', cases_path

app/views/incidents/_form.html.haml
-if @incident.errors.any?
  -@incident.errors.full_messages.each do |error|
    \- #{ error.to_s}
    %br
=simple_form_for @incident, html: { class: 'form-horizontal', multipart: true } do |f|
  %fieldset
    %legend
      =controller.action_name.capitalize
      incident:
    .control-group
      =f.input :date_of_incident
      =f.input :statute_of_limitations
      =f.input :liability, label: 'Defendant Liability'
      =f.input :alcohol, label: 'Alcohol involved?'
      =f.input :weather_factor, label: 'Weather a factor'
      =f.input :damage, label: 'Property Damage'
      =f.input :airbag, label: 'Airbag Deployed'
      =f.input :speed, label: 'Speed of Bullet Car'
      =f.input :police_report
      %br
      =f.button :submit, class: 'btn btn-primary', value: 'Add incident'

app/views/incidents/edit.html.haml
= render partial: 'form'

app/views/incidents/new.html.haml
= render partial: 'form'

app/views/incidents/show.html.haml
%h3 Case Details
%br
%table{id: 'show_case_table'}
  %tr
    %td
      %strong Case name*:
    %td
      =@case.name
  %tr
    %td
      %strong Docket no.:
    %td
      =@case.doc_number
  %tr
    %td
      %strong Judge:
    %td
      =@case.judge
  %tr
    %td
      %strong court:
    %td
      =@case.court
  %tr
    %td
      %strong plaintiff:
    %td
      =@case.plaintiff
  %tr
    %td
      %strong Defendant:
    %td
      =@case.defendant
  %tr
    %td
      %strong corporation:
    %td
      =@case.corporation
  %tr
    %td
      %strong Status:
    %td
      =@case.status
  %tr
    %td
      %strong Creation Date:
    %td
      =@case.creation_date
  %tr
    %td
      %strong Date Closed:
    %td
      =@case.date_closed
  %tr
    %td
      %strong Type*:
    %td
      =@case.main_type
  %tr
    %td
      %strong Sub-type:
    %td
      =@case.sub_type
  %tr
    %td
      %strong Description:
    %td
      =@case.description
%br
#links
  =link_to 'Edit', edit_case_path(@case)
  |
  =link_to 'Back', cases_path

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Litigo</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div id="head_bar">
    <div id="inside_head">
      <%= link_to image_tag('head.png'), root_path %>
      <div id="user_nav">
        <% if user_signed_in? %>
          Welome, <%= current_user.login %>
          <%= link_to (button_tag 'SIGN OUT', id: 'sign_out_btn'), destroy_user_session_path, method: :delete  %>
        <% end %>
      </div>
    </div>
  </div>
  <div id="head_bar_menu">
    <div id="search">
      <%= form_tag (cases_path) do text_field_tag('search', nil, placeholder: 'SEARCH') end %>
    </div>
  </div>
  <div class="container">
    <div class="row">
      <div class="span3">
        <div id="vertical_menu">Menu<br> fbhsdj</div>
      </div>
      <div class="span9"><%= yield %></div>
    </div>
  </div>

</body>
</html>